# Generated by Django 2.2.8 on 2019-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191204_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='Geplanter_Status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='Status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
