# Generated by Django 2.2.8 on 2019-12-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191204_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='Netzwerke',
        ),
    ]
