# Generated by Django 2.2.8 on 2019-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191211_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='Geplanter_Status',
        ),
        migrations.AddField(
            model_name='poll',
            name='geplanter_Status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Netzwerk'),
        ),
    ]
