# Generated by Django 2.2.8 on 2019-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191211_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='Kurzbeschreibung',
            field=models.CharField(default='', max_length=200),
        ),
    ]
